config/routes.rb
Rails.application.routes.draw do
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: :edit
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  get "/signup", to: "users#new"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  root to: "static_pages#home"
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: {maximum: 140}
  default_scope {order(created_at: :desc)}
  has_one_attached :image
  validates :image, content_type: {in: ["image/jpeg", "image/gif", "image/png"], message: "Must be a valid image format."}, size: {less_than: 5.megabytes, message: "Should be less than 5MB."}

  # def display_image
  #   image.variant(resize_to_limit: [500, 500])
  # end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :destroy

  def create
    @micropost = current_user.microposts.build(micropost_params)
    @micropost.image.attach(params[:micropost][:image])
    if @micropost.save
      flash[:notice] = "Your new micropost was successfully created!"
      redirect_to root_path
    else
      @feed_items = current_user.feed.paginate(page: params[:page])
      render "static_pages/home"
    end
  end

  def destroy
    @micropost.destroy
    flash[:notice] = "Your micropost was successfully deleted."
    redirect_to request.referrer || root_path
  end

  private

  def micropost_params
    params.require(:micropost).permit(:content, :image)
  end

  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    redirect_to root_path if @micropost.nil?
  end
end

app/views/microposts/_micropost.html.erb
<!-- <li id="micropost-<%= micropost.id %>">
  <%= link_to user_path(micropost.user) do %>
    <% if micropost.user.photo.attached? %>
      <%= cl_image_tag micropost.user.photo.key, class: "avatar-large" %>
    <% else %>
      <%= image_tag "user.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
    <% end %>
  <% end %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content">
    <%= micropost.content %>
    <%= cl_image_tag micropost.image.key, width: 500, height: 500, crop: :limit if micropost.image.attached? %>
  </span>
  <span class="timestamp">Posted <%= time_ago_in_words(micropost.created_at) %> ago.</span>
  <% if current_user?(micropost.user) %>
    <%= link_to "Delete", micropost_path(micropost), method: :delete, data: {confirm: "Are you sure?"}, class: "delete-link" %>
  <% end %>
</li> -->

<li id="micropost-<%= micropost.id %>">
  <div class="card-trip">
    <%= link_to "X", micropost_path(micropost), method: :delete, data: {confirm: "Are you sure?"}, class: "delete-link x-sign" %>
    <%= cl_image_tag micropost.image.key, width: 500, height: 500, crop: :limit if micropost.image.attached? %>
    <div class="card-trip-infos">
      <div>
        <h2><%= micropost.content %></h2>
        <p>Posted <%= time_ago_in_words(micropost.created_at) %> ago.</p>
      </div>
      <h2 class="card-trip-pricing"><%= link_to micropost.user.name, micropost.user %></h2>
      <%= link_to user_path(micropost.user) do %>
        <% if micropost.user.photo.attached? %>
          <%= cl_image_tag micropost.user.photo.key, class: "card-trip-user avatar-bordered" %>
        <% else %>
          <%= image_tag "user.png", class: "card-trip-user avatar-bordered" %>
        <% end %>
      <% end %>
    </div>
  </div>
</li>